services:
  grafana:
    image: grafana/grafana:latest
    container_name: serving-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - movie-pipeline
    restart: unless-stopped

networks:
  movie-pipeline:
    external: true

volumes:
  grafana-data:
